---
title: "celltype_enrichment"
author: "<h4>Author: <i>Brian M. Schilder</i></h4>" 
date: "<h4>Most recent update: <i>`r format( Sys.Date(), '%b-%d-%Y')`</i></h4>"
output:
  BiocStyle::html_document:
    self_contained: yes
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: show
    df_print: paged
vignette: >
    %\VignetteIndexEntry{celltype_enrichment} 
    %\usepackage[utf8]{inputenc}
    %\VignetteEngine{knitr::rmarkdown} 
editor_options: 
  markdown: 
    wrap: 72
---

```{r style, echo=FALSE, results='asis', message=FALSE}
BiocStyle::markdown()
knitr::opts_chunk$set(tidy = FALSE, message  = FALSE)
```

```{r setup, include=TRUE, message=FALSE} 
library(phenomix)

library(dplyr)
library(ggplot2)
```


# Import data

```{r}
### DeGAs loadings 
data("DEGAS_seurat")
xmat <- phenomix::extract_loadings(obj = DEGAS_seurat)
xmat <- xmat[,1:10] # Let's use just 10 components as an example

### Celltype Dataset
data("ctd_BlueLake2018_FrontalCortexOnly")
ymat <- ctd_BlueLake2018_FrontalCortexOnly[[1]]$specificity
```

# Enrichment tests

## Linear regression 

```{r}  
res_lm <- phenomix::iterate_lm(xmat = xmat, 
                               ymat = ymat) 
```

### Results 

```{r}
phenomix:::create_DT(subset(res_lm, qvalue<.05))
```

### Plot 

```{r, fig.width=7, fig.height=5}
## Only plot the top 20 significant results
data_lm <- subset(res_lm, qvalue<.05) %>%
  dplyr::slice_min(qvalue, n = 20) %>%
  dplyr::arrange(term, qvalue)

ggplot(data_lm, aes(x=trait, y=-log10(qvalue), fill=term)) +
  geom_bar(stat = "identity") +
  facet_grid(facets = gsub("_","\n",term) ~.) +
  labs(x="celltype", title="Linear regession results") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust=1)) 
```



## Gene set enrichment analysis 

```{r}
res_gsea <- phenomix::iterate_gsea(xmat = xmat, 
                                   ymat = ymat) 
```


### Results 

```{r}
phenomix:::create_DT(subset(res_gsea, qvalue<.05))
```

### Plot 

THere are no signfiicant results to plot

```{r, eval=FALSE}
## Only plot the top 20 significant results
data_gsea <- subset(res_gsea, qvalue<.05) %>%
  dplyr::slice_min(qvalue, n = 20) %>%
  dplyr::arrange(term, qvalue)
if(nrow(data_gsea)>0){
  ggplot(data_gsea, aes(x=trait, y=-log10(qvalue), fill=term)) +
  geom_bar(stat = "identity") +
  facet_grid(facets = gsub("_","\n",term) ~.) +
  labs(x="celltype", title="GSEA results") + 
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust=1))  
} 
```

 
# Session Info 

<details> 

```{r Session Info}
utils::sessionInfo()
```

</details>  

