---
title: "GWAS_Atlas"
author: "<h4>Author: <i>Brian M. Schilder</i></h4>" 
date: "<h4>Most recent update: <i>`r format( Sys.Date(), '%b-%d-%Y')`</i></h4>"
output:
  BiocStyle::html_document:
vignette: >
    %\VignetteIndexEntry{GWAS_Atlas} 
    %\usepackage[utf8]{inputenc}
    %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=TRUE, message=FALSE} 
library(phenomix) 
```


# Import data

## GWAS Atlas

```{r, eval=FALSE}
obj <- phenomix::get_GWAS_Atlas()
knitr::kable(head(obj@meta.data))
```

## HPO

```{r, eval=FALSE}
obj_hpo <- phenomix::get_HPO()
obj_hpo <- SeuratObject::RenameAssays(obj_hpo, MAGMA = "RNA")
obj_hpo$source <- "HPO"
```

# Plot UMAP

## Domains

```{r, eval=FALSE}
gg_umap <- phenomix::plot_reduction(obj = obj, 
                                    reduction = "umap", 
                                    color_var = "Domain", 
                                    size_var = "N")
```


## TF-IDF

```{r, eval=FALSE}
tfidf_res <- scNLP::plot_tfidf(object = obj, 
                               reduction = "umap", 
                               label_var = "Trait", size_var = NULL,
                               terms_per_cluster = 2) 
```

## UMAP: merged


```{r, eval=FALSE}
gg_merged <- gg_umap + tfidf_res$plot + patchwork::plot_layout(ncol = 1)
print(gg_merged)

# ggplot2::ggsave(filename = "/Desktop/phenome_decomposition/processed_data/GWAS_Atlas/UMAP_merged.pdf", 
#                 plot = gg_merged, 
#                 height = 14, 
#                 width = 10)
```

# MOFA2

```{r, eval=FALSE}
# obj <- Seurat::FindVariableFeatures(obj, nfeatures = 10000)
model_obj <-  phenomix::run_mofa2(obj = obj,  
                                  # groups = "Domain",
                                  assay = "MAGMA")

obj <- model_obj$obj
```

## Plot MOFA2 

### MOFA2 

```{r, eval=FALSE}
gg_mofa2 <- phenomix::plot_reduction(obj = obj, 
                                     color_var = "Domain",
                                     reduction = "mofa2")
```


### UMAP

```{r, eval=FALSE}
gg_mofa2umap <- phenomix::plot_reduction(obj = obj, 
                                         color_var = "Domain",
                                         reduction = "mofa2umap")
print(gg_mofa2umap)
```



# Enrichment tests

```{r, eval=FALSE}
xmat <- phenomix::extract_loadings(obj = obj, 
                                   reduction = "pca")
```


## DescartesHuman

Characterise each factor with the DescartesHuman scRNA-seq CellTypeDataset

```{r, eval=FALSE}
#### Preprare data #### 
ctd <- phenomix::get_DescartesHuman()
ymat <- ctd[[2]]$specificity
#### Run tests #####
res <- phenomix::iterate_lm(xmat = xmat,
                            ymat = ymat)
res_sig <- subset(res, qvalue<.05) 
```

### Plot enrichment 

```{r, eval=FALSE}
gg_bar <- phenomix::plot_enrichment(res = res,
                                    types = "bar")
```



## HPO 

Characterise each factor with the Human Phenotype Ontology.

```{r, eval=FALSE}
top_phenos <- phenomix::get_top_traits(obj = obj_hpo, 
                                       n_traits = 10,
                                       show_plot = FALSE)
obj_hpo_sub <- subset(obj_hpo, (HPO_id %in% top_phenos$phenotype) & n_genes>4)
# obj_hpo_sub <- subset(obj_hpo, depth>=max(depth-1, na.rm = TRUE))
ymat <- obj_hpo@assays$RNA@counts


res_hpo <- phenomix::iterate_gsea(xmat = xmat[,4:5],
                                  ymat = ymat)
res_hpo <- merge(res_hpo, obj_hpo_sub@meta.data,
                 by.x = "term", by.y = "HPO_id")
res_hpo_sig <- subset(res_hpo, qvalue<.05)
knitr::kable(res_hpo_sig)

res_hpo_PC4 <- subset(res_hpo, trait=="PC_4" & depth>10)%>% dplyr::arrange(pvalue)
# data.table::fwrite(res_hpo_PC4[,c("term","trait",
#                                   "HPO_label","group_depth2","depth","pvalue")],
#                    "/Desktop/GWASatlas_HPO.enrich.csv")
```




# Parkinson's 

## Get top

```{r, eval=FALSE}
top_factors <- phenomix::get_top_factors(obj = obj, 
                                         reduction = "pca", 
                                         term = "parkinson", 
                                         search_col = "Trait")
top_features <- phenomix:: get_top_features(obj = obj, 
                                           reduction = "pca",
                                           n_features = 5,
                                           factors = names(top_factors))
top_phenos <- phenomix::get_top_traits(obj = obj, 
                                           reduction = "pca", 
                                           n_traits = 10, 
                                           show_plot = FALSE)
top_phenos_table <- subset(top_phenos, factor %in% names(top_factors))[,c("Trait",
                                                                          "factor",
                                                      "loading",
                                                      "seurat_clusters",
                                                      "SubchapterLevel")]
data.table::fwrite(top_phenos_table, "/Desktop/top_phenos_table.csv")



gprof <- run_gprofiler(obj = obj,
                                  reduction = "pca",
                                 n_features = 100,
                                 factors = 4)

```

## Find markers

```{r, eval=FALSE}
dat$PD <- grepl("parkinson",dat$Trait, ignore.case = TRUE)

dat <- Seurat::SetIdent(dat, value="PD")
PD_markers <- Seurat::FindMarkers(object = dat, ident.1=TRUE)
data.table::fwrite(PD_markers,
                   "/Desktop/phenome_decomposition/processed_data/GWAS_Atlas/PD_markers.csv.gz")
```



# Trait-trait similarity

```{r, eval=FALSE}
mat <- WGCNA::cor(obj@assays$MAGMA@data)
mat <-  as(as(mat,"sparseMatrix"),"Graph")
obj@graphs$MAGMA_cor <- mat

obj <- phenomix::compute_cor(obj = obj, 
                             assay = "MAGMA")
knn <- phenomix::find_neighbors(obj = obj, 
                                graph_name = "MAGMA_cor",
                                var1_search = "alzheimer", 
                                label_col = "Trait")
gg_cor <- phenomix::plot_trait_cor(knn = knn, 
                                   top_n = 10)

knitr::kable(head(knn))
```

# Session Info 

<details> 

```{r Session Info}
utils::sessionInfo()
```

</details>  

