---
title: "hexSticker"
author: "<h4>Author: <i>Brian M. Schilder</i></h4>" 
date: "<h4>Most recent update: <i>`r format( Sys.Date(), '%b-%d-%Y')`</i></h4>"
output: rmarkdown::html_vignette
editor_options: 
  chunk_output_type: inline
vignette: >
  %\VignetteIndexEntry{hexSticker}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = T, fig.width = 7, fig.height = 5, root.dir=here::here())
knitr::opts_knit$set(root.dir=here::here())
```

```{r setup, include=TRUE, message=FALSE} 
library(hexSticker)

library(dplyr)
library(ggplot2)
```

You can make awesome hex stickers for your R packages using [hexSticker](https://github.com/GuangchuangYu/hexSticker). 

# phenomix

Subplot image from [Geneshot_ontologies](https://github.com/bschilder/Geneshot_ontologies) project.

```{r, eval=F}   
img1 <- here::here("inst/images/geneshot.UMAP.layer2.pdf")
# img2 <- "../images/phoenix_pixel.png"

sticker(subplot = img1, package="phenomix", p_size=20, s_x=1, s_y=.7,  s_width = .8,
        h_fill = "black", h_color = "#f504f9",spotlight = FALSE, white_around_sticker=TRUE,
        filename=here::here("inst/hex/phenomix.png"))

```


# Session Info 

<details> 

```{r Session Info}
utils::sessionInfo()
```

</details>  

