---
title: "map_snps2genes"
author: "Brian M. Schilder"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{map_snps2genes} 
    %\usepackage[utf8]{inputenc}
    %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=TRUE} 
library(phenomix)    
```

# Download data

## MAGMA files

```{r}

```

### Construct gene x trait matrix

Construct gene x trait matrix from gene-level MAGMA results across multiple GWAS traits.

```{r, eval=FALSE}
X <- phenomix::magma_matrix(magma_files = magma_files,
                            metric = "ADJ_ZSTAT") 
```

## ABC

ABC method requires hg19 at the moment.

```{r, eval=FALSE}
metagwas <- subset(metagwas_all, build_inferred=="GRCH37")
```


```{r, eval=FALSE}
# preload file to make faster 
abc <- phenomix::import_abc(dataset = "Nasser2020")

{ 
  start <- Sys.time()
  abc_hits <- parallel::mclapply(seq(1,nrow(metagwas)),
                                 function(i){
    phenomix:::message_parallel("Mapping: ",metagwas$id[i])
    tryCatch(expr = {
      map_snps2genes(sumstats_file = metagwas$path[i],
                             method = "abc",
                             abc = abc) 
    }, error = function(x){x})
  }, mc.cores = 1) |> `names<-`(metagwas$id)
  phenomix:::report_time(start)
}

saveRDS(abc_hits,"/Desktop/abc_hits.rds")
abc_hits <- readRDS("/Desktop/abc_hits.rds")

metric <- "ZSTAT"
abc_matrix <- parallel::mclapply(names(abc_hits), 
                                 function(x){  
  # data.table::setnames(dat, "SYMBOL","GENE")
  phenomix:::message_parallel(x)
  dat <- abc_hits[[x]]
  dat <- na.omit(dat,"ZSTAT")
  data.table::setkey(dat, "GENE") 
  data.table::setnames(dat, old = metric, new = x)
  return(dat[,c("GENE",..x)])
  # if(nrow(dat)>0){
  #   return( dat[,c("GENE",..x)])
  # } else {return(NULL)}
  # return( dat[,c("GENE","ZSTAT")])
},  mc.cores = 1) |>
  # plyr::compact() |>
  base::Reduce(f = function(x,y){merge(x,y,all.x=TRUE,all.y=TRUE)})


abc_gene_counts <- unlist(lapply(abc_hits,nrow))
magma_genes_counts <- Matrix::colSums(magma_matrix>0)
```






# Variance partition

Use a linear mixed model to determine how much each metadata attribute affects each GWAS.

```{r, eval=FALSE}
#### Run ####
varPart <- phenomix::run_variancePartition(obj = magma_matrix, 
                                           metadata = metagwas_all, 
                                           is_opengwas = TRUE)
#### Plot ####
varPlots <- phenomix::plot_variancePartition(varPart = varPart) 
```


# Reduce dimensions


## PCA

```{r, eval=FALSE}
#### Run ####
pca <- phenomix::run_pca(mat = magma_matrix)
#### Plot ####
gg_pca <- plot_reduction(obj = pca, 
                         metadata = metagwas_all, 
                         color_var = "trait_group",
                         label_var = "trait",
                         size_var = "N")
##### Find top loaded genes per PC ####
top_genes <- get_top_features(pca)
##### Find top factors for a given set of phenotypes ####
top_factors <- get_top_factors(obj=pca,
                               metadata = metagwas_all,
                               term = "parkinson") 
#### Run GSEA of PCs ####
gres <- run_gprofiler(obj = pca)
```


### Sparse SVD

```{r, eval=FALSE}
#### Run ####
ssvd <- phenomix::run_sparsesvd(mat = magma_matrix)
#### Plot ####
gg_ssvd <- plot_reduction(obj = ssvd,
                          metadata = metagwas_all,
                          color_var = "trait_group", 
                          label_var = "trait",
                          size_var = "N") 

#### Get top loaded genes per PC ####
top_genes <- get_top_features(obj = ssvd)
##### Find top factors for a given set of phenotypes ####
top_factors <- get_top_factors(obj=ssvd,
                               metadata = metagwas_all,
                               term = "parkinson") 
#### Run GSEA of PCs ####
gres <- run_gprofiler(obj = ssvd)
```


### UMAP

```{r, eval=FALSE}
#### Run ####
umap <- phenomix::run_umap(mat = magma_matrix) 
#### Plot ####
gg_umap <- plot_reduction(obj = umap,
                          metadata = metagwas_all,
                          color_var = "trait_group", 
                          label_var = "trait",
                          size_var = "N")
#### Get top loaded genes per PC #### 
top_genes <- get_top_features(umap)
#### Run GSEA of PCs ####
gres <- run_gprofiler(obj = umap)
```




# Session Info

<details>

```{r}
utils::sessionInfo()
```

</details>
