---
title: "phenomix"
author: "<h4>Author: <i>Brian M. Schilder</i></h4>" 
date: "<h4>Most recent update: <i>`r format( Sys.Date(), '%b-%d-%Y')`</i></h4>"
output:
  rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{phenomix} 
    %\usepackage[utf8]{inputenc}
    %\VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=TRUE, message=FALSE} 
library(phenomix) 
```

# Import data

## HPO loadings 

```{r}
obj <- phenomix::get_HPO()
xmat <- scKirby::get_varm(obj = obj, 
                          keys = "pca")[[1]]
xmat <- xmat[,seq(10)] # Let's use just 10 components as an example
```

## Celltype Dataset

```{r}
ctd <- phenomix::get_ctd()
ymat <- ctd[[1]]$specificity
```

# Enrichment tests

## Linear regression 

```{r}  
res_lm <- phenomix::iterate_lm(xmat = xmat, 
                               ymat = ymat) 
```

### Results 

```{r}
knitr::kable(res_lm[qvalue<.05,])
```

### Plot 

```{r, fig.width=7, fig.height=5}
gg_bar <- phenomix::plot_enrichment(res = res_lm, 
                                    types = "bar")
```


## Gene set enrichment analysis 

```{r}
res_gsea <- phenomix::iterate_gsea(xmat = xmat, 
                                   ymat = ymat) 
```


### Results 

There are 1 significant result: PC_10 is enriched for Pericytes.

```{r}
knitr::kable(res_gsea[qvalue<.05,])
```

 
# Session Info 

<details> 

```{r Session Info}
utils::sessionInfo()
```

</details>  

