#' Extract loadings
#'
#' Extract loadings from various object types.
#'
#' @param obj Object of class:
#' \itemize{
#' \item{\code{DimReduc}}
#' \item{\code{Seurat}}
#' \item{\code{prcomp}}
#' \item{\code{list} : }{Generated by \code{run_[tools]} decomposition function.}
#' }
#' @param reduction Which reduction to extract from.
#' Defaults to first available reduction.
#' Only used if \code{obj} is of class \code{Seurat}.
#' @param verbose Print messages.
#'
#' @export
#' @importFrom methods is
#' @importFrom Seurat Reductions
extract_loadings <- function(obj,
                             reduction = NULL,
                             verbose = TRUE) {

    # obj <- DEGAS_contributionGene; obj <- scNLP::pseudo_seurat
    if (methods::is(obj, "DimReduc")) {
        messager("Extracting loadings from DimReduc.", v = verbose)
        DR <- obj
        loadings <- DR@feature.loadings
    } else if (methods::is(obj, "Seurat")) {
        if (is.null(reduction)) reduction <- Seurat::Reductions(obj)[1]
        messager("Extracting loadings from Seurat reduction: ",
            reduction,
            v = verbose
        )
        DR <- obj@reductions[[reduction]]
        loadings <- DR@feature.loadings
    } else if (methods::is(obj, "prcomp")) {
        messager("Extracting loadings from prcomp.", v = verbose)
        loadings <- obj$rotation
    } else if (methods::is(obj)) {
        messager("Extracting loadings from lda.", v = verbose)
        loadings <- obj$scaling
    } else if (methods::is(obj, "list") &
        methods::is(obj, "AssayData")) {
        messager("Extracting loadings from list.", v = verbose)
        if ("pca_models" %in% names(obj)) {
            loadings <- obj$pca_models[[1]]$rotation
        } else if ("v" %in% names(obj)) {
            loadings <- obj$v
        } else if ("V" %in% names(obj)) {
            loadings <- obj$V
        } else {
            stop("No loadings could be identified.")
        }
    } else if (is_matrix(obj) ){
        messager("Interpretting obj as matrix with feature loadings.",
                 v=verbose)
        loadings <- obj
    } else {
        stop("No loadings could be identified.")
    }
    if (is.null(colnames(loadings))) {
        messager("Renaming columns with 'dimX'.", v = verbose)
        colnames(loadings) <- paste0("dim", seq(1, ncol(loadings)))
    }
    return(loadings)
}
