#' Get CellTypeDataset: DescartesHuman
#'
#' Import the DescartesHuman CellTypeDataset (CTD) generated by
#' \href{https://github.com/NathanSkene/EWCE}{EWCE}.
#'
#' Contains mean expression (\emph{mean_exp}) matrices from sn/scRNA-seq
#' data collected across many tissues the human embryo.
#' Also contains precomputed \emph{specificity} and
#' \emph{specificity_quantiles} matrices.
#'
#' @source
#' \code{
#' save_path <- file.path("/Desktop/model_celltype_conservation/processed_data",
#'                        "EWCE/standardized_CTD/DescartesHuman.rds")
#' piggyback::pb_upload(file = save_path,
#'                      repo = "neurogenomics/phenomix",
#'                      overwrite = TRUE)
#' }
#' @return \pkg{Seurat} object
#' @export
get_DescartesHuman <- function() {
    tmp <- get_data(fname = "DescartesHuman.rds")
    obj <- readRDS(tmp)
    return(obj)
}
