#' Get CellTypeDataset: ctd_BlueLake2018_FrontalCortexOnly
#'
#' Import the ctd_BlueLake2018_FrontalCortexOnly CellTypeDataset (CTD)
#' generated by \href{https://github.com/NathanSkene/EWCE}{EWCE}.
#'
#' Contains mean expression (\emph{mean_exp}) matrices from sn/scRNA-seq
#' data collected across many tissues the human embryo.
#' Also contains precomputed \emph{specificity} and
#' \emph{specificity_quantiles} matrices.
#'
#' @source \href{ https://pubmed.ncbi.nlm.nih.gov/29227469/}{Publication}
#' @source \href{https://www.nature.com/articles/s41467-019-11953-9}{Publication}
#' @source
#' \code{
#' save_path <- file.path(
#'     "/Desktop/model_celltype_conservation/processed_data/EWCE",
#'     "standardized_CTD/BlueLake2018_FrontalCortexOnly.rds")
#' piggyback::pb_upload(file = save_path,
#'                      repo = "neurogenomics/phenomix",
#'                      overwrite = TRUE)
#' }
#' @return \pkg{Seurat} object
#' @export
get_BlueLake2018_FrontalCortexOnly <- function() {
    tmp <- get_data(fname = "BlueLake2018_FrontalCortexOnly.rds")
    obj <- readRDS(tmp)
    return(obj)
}
