#' Plot HPO pseudotime
#' 
#' Plot the Human Phenotype Ontology (HPO) in genomic latent space,
#' then compute pseudotime trajectories between a subset of phenotypes that
#' are symptoms of a given disease (or set of diseases).
#' @param obj \link{Seurat} object of HPO terms generated by \link{prepare_hpo}.
#' @param disease_ids One or more disease IDs found within \code{p2d}.
#' @inheritParams prepare_hpo
#' @inheritParams monocle3::learn_graph
#' @inheritParams monocle3::order_cells
#' @inheritDotParams monocle3::plot_cells
#' @export
#' @examples
#' obj <- get_HPO()
#' out <- plot_hpo_pseudotime(obj)
plot_hpo_pseudotime <- function(obj,
                                p2d = HPOExplorer::load_phenotype_to_genes(1),
                                disease_ids=p2d$disease_id[1:3],
                                root_cells = NULL,
                                id_col = NULL,
                                learn_graph_control=list(
                                    prune_graph=FALSE,
                                    nn.cores=KGExplorer::set_cores()$workers),
                                use_partition=TRUE,
                                merge_trajectories = TRUE,
                                symptom_color="red",
                                bg_colors=c("#5000ff","white"),
                                trajectory_graph_color=ggplot2::alpha("white",.8),
                                title_col=NULL,
                                title_width=100,
                                color_by_symptoms=TRUE,
                                color_cells_by = if(color_by_symptoms){
                                    "is_symptom" }else {"cluster"},
                                point_alpha=.5,
                                add_density=TRUE,
                                density_filled=FALSE,
                                density_adjust=1,
                                density_alpha=point_alpha,
                                title=stringr::str_wrap(
                                    paste0(unique(disease_ids),
                                           collapse = "; "),
                                    20*2.5
                                ),
                                show_plot=TRUE,
                                ...
                                ){
    # obj=readRDS("../thesis/inst/pages/chapter2/data/hpo_ot_integratedV5.rds"); id_col="hp_id";
    # disease_ids <- c( "OMIM:104300","OMIM:104310","OMIM:606889","OMIM:607822","OMIM:608907","ORPHA:1020","ORPHA:280397")
    disease_id <- NULL;
    disease_ids <- unique(disease_ids)
    #### Map p2d to Mondo IDs ####
    p2d <- data.table::copy(p2d)[,.SD[1],by=c("hpo_id","disease_id")]
    p2d <- HPOExplorer::add_mondo(phenos = p2d, 
                                  allow.cartesian=TRUE) 
    #### Map disease IDs to Mondo IDs ####
    disease_map <- HPOExplorer::add_mondo(
        phenos=data.table::data.table(disease_id=disease_ids),
        allow.cartesian=TRUE)
    disease_ids <- unique(c(disease_ids,unique(disease_map$mondo_id))) 
    disease_ids <- map_id_sep(unique(disease_ids))
    #### Run pseudotime: merged ####
    if(isTRUE(merge_trajectories)){
        out <- run_hpo_pseudotime(obj = obj, 
                                  disease_ids = disease_ids,
                                  p2d = p2d, 
                                  id_col = id_col,
                                  root_cells = root_cells,
                                  learn_graph_control = learn_graph_control,
                                  use_partition=use_partition,
                                  color_by_symptoms=color_by_symptoms, 
                                  color_cells_by=color_cells_by,
                                  point_alpha=point_alpha,
                                  title=title,
                                  symptom_color=symptom_color,
                                  bg_colors=bg_colors,
                                  trajectory_graph_color = trajectory_graph_color,
                                  add_density=add_density,
                                  density_filled=density_filled,
                                  density_adjust=density_adjust,
                                  density_alpha=density_alpha,
                                  ...)
        if(isTRUE(show_plot)) methods::show(out$plot)
    } else {
    #### Run pseudotime: split ####
        out <- list()
        out[["subplots"]] <- lapply(stats::setNames(disease_ids,
                                                    disease_ids),
                                    function(d){
            if(!is.null(title_col) && 
                         title_col %in% names(p2d)){
                # p2d <- HPOExplorer::add_disease(p2d) 
                title <- p2d[!is.na(get(title_col)) &
                                  disease_id==d][[title_col]][1]
                subtitle <- d
            } else {
                title <- d
                subtitle <- NULL
            }
          run_hpo_pseudotime(obj = obj, 
                             disease_ids = d,
                             p2d = p2d, 
                             id_col = id_col,
                             root_cells = root_cells,
                             learn_graph_control = learn_graph_control,
                             use_partition=use_partition,
                             title = stringr::str_wrap(title,
                                                       width = title_width),
                             subtitle=subtitle,
                             point_alpha=point_alpha,
                             color_by_symptoms=color_by_symptoms,
                             color_cells_by=color_cells_by,
                             add_density=add_density,
                             density_filled=density_filled,
                             density_adjust=density_adjust,
                             density_alpha=density_alpha,
                             ...)
        })
        out[["plot"]] <- patchwork::wrap_plots(lapply(out$subplots,
                                                      function(x)x$plot)) +
            patchwork::plot_layout(guides = "collect",
                                   axes = "collect", 
                                   axis_titles = "collect")
        if(show_plot) methods::show(out[["plot"]] )
    }
    return(out)
    
    # pseudo_dt <- t(cds@principal_graph_aux$UMAP$pr_graph_cell_proj_dist)|>`colnames<-`(c("umap1","umap2"))
    
    # gm <- ref@graphs$freq_nn[highlights$hpo_id,
    #                           highlights$hpo_id]
    # g <- igraph::graph_from_adjacency_matrix(gm)
    # gdt <- KGExplorer::graph_to_dt(g)[object!=subject]
    # ggraph(g, layout = 'stress') + 
    #     geom_edge_density() + 
    #     geom_edge_link(alpha = 0.25)
    # dp <- Seurat::DimPlot(ref, 
    #                       group.by = disease_id,
    #                       cols.highlight = "red",
    #                       alpha = .7,
    #                       sizes.highlight = highlights[[disease_id]],
    #                       cells.highlight = list( highlights[["hpo_id"]])|>
    #                           `names<-`(disease_id))
    # highlight_df <- subset(dp[[1]]$data,highlight!="Unselected")
    # 
    # highlight_dt <- merge(gdt,
    #                       data.table::data.table(highlight_df,keep.rownames = "subject"),
    #                       by="subject")|>
    #     merge(data.table::data.table(highlight_df,keep.rownames = "object"),
    #           by=c("object","highlight",disease_id)) |>
    #     data.table::setnames(c("umap_1.x","umap_2.x","umap_1.y","umap_2.y"),
    #                          c("x","y","xend","yend"))
    # # ggplot2::ggplot()
    # dp + ggplot2::geom_segment(data = highlight_dt,
    #                            mapping = ggplot2::aes(x = x,
    #                                                   xend = xend,
    #                                                   y = y,
    #                                                   yend = yend),
    #                            inherit.aes = FALSE)
    # dp+
    #     ggplot2::geom_step(data = highlight_df, 
    #                        ggplot2::aes(x=umap_1,
    #                                     y=umap_2)) 
}
