#' Plot HPO pseudotime
#' 
#' Plot the Human Phenotype Ontology (HPO) in genomic latent space,
#' then compute pseudotime trajectories between a subset of phenotypes that
#' are symptoms of a given disease (or set of diseases).
#' @param obj \link{Seurat} object of HPO terms generated by \link{prepare_hpo}.
#' @param disease_ids One or more disease IDs found within \code{dt_genes}.
#' @inheritParams prepare_hpo
#' @inheritParams monocle3::learn_graph
#' @inheritDotParams monocle3::plot_cells
#' @export
#' @examples
#' obj <- get_HPO()
#' out <- plot_hpo_pseudotime(obj)
plot_hpo_pseudotime <- function(obj,
                                dt_genes = HPOExplorer::load_phenotype_to_genes(1),
                                disease_ids=dt_genes$disease_id[1:3],
                                learn_graph_control=list(prune_graph=FALSE),
                                merge_trajectories = TRUE,
                                symptom_color="red",
                                bg_colors=c("#5000ff","white"),
                                trajectory_graph_color=ggplot2::alpha("white",.8),
                                title_col=NULL,
                                title_width=100,
                                color_by_symptoms=TRUE,
                                point_alpha=.5,
                                show_plot=TRUE,
                                ...
                                ){
    disease_id <- NULL;
    colnames(obj) <- replace_char_fun(colnames(obj))
    disease_ids <- unique(disease_ids)
    #### Add disease metadata
    ## Using gene overlap (670998 p2d pairs) ##
    # nrow(unique(dt_genes[,c("hpo_id","disease_id")]))
    if(isTRUE(merge_trajectories)){
        out <- run_hpo_pseudotime(obj = obj, 
                                  disease_ids = disease_ids,
                                  dt_genes = dt_genes, 
                                  learn_graph_control = learn_graph_control,
                                  color_by_symptoms=color_by_symptoms,
                                  title=stringr::str_wrap(
                                      paste0(unique(disease_ids),
                                             collapse = "; "),
                                      20*2.5
                                  ),
                                  point_alpha=point_alpha,
                                  symptom_color=symptom_color,
                                  bg_colors=bg_colors,
                                  trajectory_graph_color = trajectory_graph_color,
                                  ...)
        if(show_plot) methods::show(out$plot)
    } else {
        out <- list()
        out[["subplots"]] <- lapply(stats::setNames(disease_ids,
                                                    disease_ids),
                                    function(d){
            if(!is.null(title_col) && 
                         title_col %in% names(dt_genes)){
                # dt_genes <- HPOExplorer::add_disease(dt_genes) 
                title <- dt_genes[!is.na(get(title_col)) &
                                  disease_id==d][[title_col]][1]
                subtitle <- d
            } else {
                title <- d
                subtitle <- NULL
            }
          run_hpo_pseudotime(obj = obj, 
                             disease_ids = d,
                             dt_genes = dt_genes, 
                             learn_graph_control = learn_graph_control,
                             title = stringr::str_wrap(title,
                                                       width = title_width),
                             subtitle=subtitle,
                             point_alpha=point_alpha,
                             color_by_symptoms=color_by_symptoms,
                             ...)
        })
        out[["plot"]] <- patchwork::wrap_plots(lapply(out$subplots,
                                                      function(x)x$plot)) +
            patchwork::plot_layout(guides = "collect",
                                   axes = "collect", 
                                   axis_titles = "collect")
        if(show_plot) methods::show(out[["plot"]] )
    }
    return(out)
    
    # pseudo_dt <- t(cds@principal_graph_aux$UMAP$pr_graph_cell_proj_dist)|>`colnames<-`(c("umap1","umap2"))
    
    # gm <- ref@graphs$freq_nn[highlights$hpo_id,
    #                           highlights$hpo_id]
    # g <- igraph::graph_from_adjacency_matrix(gm)
    # gdt <- KGExplorer::graph_to_dt(g)[object!=subject]
    # ggraph(g, layout = 'stress') + 
    #     geom_edge_density() + 
    #     geom_edge_link(alpha = 0.25)
    # dp <- Seurat::DimPlot(ref, 
    #                       group.by = disease_id,
    #                       cols.highlight = "red",
    #                       alpha = .7,
    #                       sizes.highlight = highlights[[disease_id]],
    #                       cells.highlight = list( highlights[["hpo_id"]])|>
    #                           `names<-`(disease_id))
    # highlight_df <- subset(dp[[1]]$data,highlight!="Unselected")
    # 
    # highlight_dt <- merge(gdt,
    #                       data.table::data.table(highlight_df,keep.rownames = "subject"),
    #                       by="subject")|>
    #     merge(data.table::data.table(highlight_df,keep.rownames = "object"),
    #           by=c("object","highlight",disease_id)) |>
    #     data.table::setnames(c("umap_1.x","umap_2.x","umap_1.y","umap_2.y"),
    #                          c("x","y","xend","yend"))
    # # ggplot2::ggplot()
    # dp + ggplot2::geom_segment(data = highlight_dt,
    #                            mapping = ggplot2::aes(x = x,
    #                                                   xend = xend,
    #                                                   y = y,
    #                                                   yend = yend),
    #                            inherit.aes = FALSE)
    # dp+
    #     ggplot2::geom_step(data = highlight_df, 
    #                        ggplot2::aes(x=umap_1,
    #                                     y=umap_2)) 
}